name = "departs-app"
compatibility_date = "2026-03-17"

[secrets]
required = ["GOLEMIO_API_KEY"]

[observability]
enabled = true
[[flagship]]
binding = "FLAGS"
app_id = "4c77e6bb-e404-4772-b1c8-5ef5af4cf55a"
